pipeline {
    agent any
    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/chaitanyazunzurkar/django_project.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t chaitanyazunzurkar/django_project .'
            }
        }
        stage('Login to Docker Hub') {
            steps {
                withCredentials([string(credentialsId: 'docker-hub-password', variable: 'DOCKER_PASSWORD')]) {
                    sh 'echo $DOCKER_PASSWORD | docker login -u chaitanyazunzurkar --password-stdin'
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                sh 'docker push chaitanyazunzurkar/django_project'
            }
        }
    }
}
